#!/bin/bash

mount /dev/ ${ecroot}/dev/ --bind -o ro
mount -t devpts none ${ecroot}/dev/pts -o gid=5
mount --bind $SYS_PREFIX/var/portage/gentoo ${ecroot}/var/portage/gentoo
mount --bind $SYS_PREFIX/var/portage/overlay ${ecroot}/var/portage/overlay -o ro
mount --bind $SYS_PREFIX/var/portage/packages ${ecroot}/var/portage/packages -o ro
mount -t proc none ${ecroot}/proc -o ro
mount -t tmpfs none ${ecroot}/run
