#!/bin/bash

. ./env

[ "$ecroot" == ""  ] && ecroot="$SYS_PREFIX/var/gentoo/system-gentoo"
[ "$ecroot" == ""  ] && ecroot="/var/gentoo/system-gentoo"

umount ${ecroot}/run
umount ${ecroot}/proc
umount ${ecroot}/var/portage/gentoo
umount ${ecroot}/var/portage/overlay
umount ${ecroot}/var/portage/packages
umount ${ecroot}/dev/pts
umount ${ecroot}/dev
