#!/bin/bash

ecroot="/var/gentoo/arm64"

mount /dev/ ${ecroot}/dev/ --bind -o ro

mount -o loop /var/gentoo/x86_64/var/gentoo/portage-20191001.squashfs ${ecroot}/usr/portage

#mount -o loop /var/gentoo/x86_64/var/gentoo/portage-20190227.squashfs ${ecroot}/usr/portage

#mount --bind /var/portage/distfiles ${ecroot}/var/portage/distfiles -o ro
#mount --bind /var/portage/packages ${ecroot}/var/portage/packages -o ro
mount -t proc none ${ecroot}/proc -o ro
#mount -t tmpfs none ${ecroot}/var/cache
#mount -t tmpfs none ${ecroot}/var/log
#mount -t tmpfs none ${ecroot}/run
mount -t devpts none ${ecroot}/dev/pts -o gid=5
mount -t tmpfs none ${ecroot}/dev/shm -o mode=1777

LC_ALL=C chroot ${ecroot} $*

umount ${ecroot}/dev/shm
umount ${ecroot}/dev/pts
umount ${ecroot}/dev
umount ${ecroot}/usr/portage
#umount ${ecroot}/var/portage/distfiles
#umount ${ecroot}/var/portage/packages
umount ${ecroot}/proc
#umount ${ecroot}/var/cache
#umount ${ecroot}/var/log
#umount ${ecroot}/run
