#!/bin/bash

COLORTERM=""

ecroot="/var/gentoo/x86_64"

mount --bind /dev/ ${ecroot}/dev/ -o ro
mount -t tmpfs none ${ecroot}/dev/shm -o mode=1777
mount -t devpts none ${ecroot}/dev/pts -o gid=5
mount ${ecroot}/../portage ${ecroot}/usr/portage
mount -t proc none ${ecroot}/proc -o ro
mount -t tmpfs none ${ecroot}/run

[ ! -f x86_64/root/.bashrc ] && mkdir -p ${ecroot}/root && echo "PS1=\"chroot x86_64 \$PS1\"" > x86_64/root/.bashrc

LC_ALL=C chroot ${ecroot} $*

umount ${ecroot}/dev/shm
umount ${ecroot}/dev/pts
umount ${ecroot}/dev
umount ${ecroot}/usr/portage
umount ${ecroot}/proc
umount ${ecroot}/run
