#!/bin/bash

PREFIX="/var/gentoo/arm64"

. $PREFIX/var/gentoo/version

ecroot="$PREFIX/var/gentoo/system-arm64-gentoo"

mount /dev/ ${ecroot}/dev/ --bind -o ro
mount -t devpts none ${ecroot}/dev/pts -o gid=5
#mount -o loop $PREFIX/var/gentoo/portage-$P.squashfs ${ecroot}/usr/portage
mount --bind $PREFIX/usr/portage ${ecroot}/usr/portage
mount --bind $PREFIX/var/portage/packages ${ecroot}/var/portage/packages -o ro
mount -t proc none ${ecroot}/proc -o ro
mount -t tmpfs none ${ecroot}/run

LC_ALL=C chroot ${ecroot} $*

umount ${ecroot}/dev/pts
umount ${ecroot}/dev
umount ${ecroot}/usr/portage
umount ${ecroot}/var/portage/packages
umount ${ecroot}/proc
umount ${ecroot}/run
