#!/bin/bash

PREFIX=/var/gentoo/arm64

P=$PWD

[ "$DIR" == "" ] && DIR="files"
[ "$TEMPLATE" == "" ] && TEMPLATE=".cp-files"

find $TEMPLATE -type d | sed s/"$TEMPLATE"/"$DIR"/ | grep -v '*' | xargs mkdir -p
FILES=$(find $TEMPLATE -type f | sed s/"$TEMPLATE\/"//)

echo "$FILES"

cd $PREFIX && cp --parents -r $FILES $P/$DIR

cd $P
