#!/bin/bash

P="../ofs-boot"

$P/mk-loader
$P/mk-ro
RW_SIZE=256M $P/mk-rw
mkdir -p gentoo/system
mv ro gentoo/
mv rw gentoo/
N=$(ls kernel*.tar.xz | sed s/kernel/ofs-boot-base/)
XZ_OPT="-9 -T0 -v" tar -cJ efi gentoo > "$N"
rm -r efi gentoo
