#!/bin/bash

BP=$(echo "$0" | sed s/$(basename $0)//)

KV=$(ls | grep kernel*.tar.xz | sed s/kernel-// | sed s/.tar.xz//)

if [ "$KV" == "" ] ; then
echo "Kernel not found!"
exit 1
fi

if [ ! -d ./kernel-$KV ] ; then
echo "Unpack kernel.."
tar -xJpf ./kernel-$KV.tar.xz
[ -d ./kernel-$KV/lib64 ] && mv ./kernel-$KV/lib64 ./kernel-$KV/lib
fi

DIR=ro-temp

mkdir -p $DIR

cp --preserve $BP/base/* -r $DIR
cp --preserve $BP/user/* -r $DIR
cp --preserve ./kernel-$KV/boot/ -r $DIR
cp --preserve ./kernel-$KV/lib/ -r $DIR

N=base

if [ -f ./ro.include ] ; then
CP=$PWD
. ./ro.include ; RET=$?
cd $CP
[ "$RET" != "0" ] && echo "Error in ro.include!" && exit 1
fi

mkdir -p ro

[ -f "ro/ro-$N-$KV.squashfs" ] &&  echo "File (ro/ro-$N-$KV.squashfs) exist! Renaming..." && sleep 5 && mv ro/ro-$N-$KV.squashfs ro/ro-$N-$KV.squashfs-

mksquashfs $DIR ro/ro-$N-$KV.squashfs -comp xz

rm -rf $DIR

GC=efi/grub-efi.cfg

[ ! -f "$GC" ] && mkdir -p ./efi && cp $BP/loader/efi/grub-efi.cfg ./efi

V=$(echo "$KV" | cut -d'-' -f 1)
R=$(echo "$KV" | cut -d'-' -f 2 | grep 'r')
[ "$R" != "" ] && sed s/kr=.*$/"kr=-$R"/ -i $GC
sed s/kv=.*$/kv=$V/ -i $GC
[ "$R" != "" ] && echo "kernel: $V-$R" || echo "kernel: $V"
sed s/lro=.*$/lro=ro-$N-$KV.squashfs/ -i $GC
if [ "$SV" == "" ] ; then [ "$R" == "" ] && SV=$(echo $KV | sed s/"$V-"// | sed s/"gkc"//) || SV=$(echo $KV | sed s/"$V-"// | sed s/"$R-"// | sed s/"gkc"//) ; fi
sed s/lsystem=.*$/lsystem=system-gentoo-$SV.squashfs/ -i $GC
