#!/bin/bash

. ./env
. $SYS_PREFIX/var/gentoo/version

ecroot="$SYS_PREFIX/var/gentoo/system-gentoo"

mount /dev/ ${ecroot}/dev/ --bind -o ro
mount -t devpts none ${ecroot}/dev/pts -o gid=5
mount --bind $SYS_PREFIX/usr/portage ${ecroot}/usr/portage
mount --bind $SYS_PREFIX/var/portage/packages ${ecroot}/var/portage/packages -o ro
mount -t proc none ${ecroot}/proc -o ro
mount -t tmpfs none ${ecroot}/run

unset SYS_PREFIX
LC_ALL=C chroot ${ecroot} $*

umount ${ecroot}/dev/pts
umount ${ecroot}/dev
umount ${ecroot}/usr/portage
umount ${ecroot}/var/portage/packages
umount ${ecroot}/proc
umount ${ecroot}/run
