#!/bin/bash

. /var/gentoo/version

ecroot="/var/gentoo/system-gentoo"

mkdir ${ecroot}

CP=$PWD
cd tools
export DIR=_
TEMPLATE=.s.files ../cp-files
cp _/* -r ${ecroot}
rm -r $DIR
cp emerge-cross-system/* -r ${ecroot}
cd $CP

sed s/"-j[0-9]*"/"-j2"/ -i $ecroot/etc/portage/make.conf
sed s/"FEATURES"/"#FEATURES"/ -i $ecroot/etc/portage/make.conf
sed s/"#"// -i $ecroot/etc/portage/profile/package.provided

mount /dev/ ${ecroot}/dev/ --bind -o ro
mount -t devpts none ${ecroot}/dev/pts -o gid=5
mount -t proc none ${ecroot}/proc -o ro
mount --bind /usr/portage ${ecroot}/usr/portage
mount --bind /var/portage/ ${ecroot}/var/portage -o ro
mount -t tmpfs none ${ecroot}/run

export PKGDIR=${ecroot}/var/portage/packages

export LC_ALL=C
export LANG=C

ROOT=${ecroot} SYSROOT=${ecroot} PORTAGE_CONFIGROOT=${ecroot} emerge --jobs=16 -1 -K --nodeps baselayout app-alternatives/awk app-alternatives/bc app-alternatives/bzip2 app-alternatives/cpio app-alternatives/gzip app-alternatives/lex app-alternatives/sh app-alternatives/tar app-alternatives/yacc
ROOT=${ecroot} SYSROOT=${ecroot} PORTAGE_CONFIGROOT=${ecroot} emerge --jobs=16 -1 -K --nodeps coreutils glibc app-arch/bzip2 portage bash ncurses readline python python-exec app-arch/gzip sys-libs/zlib libffi findutils sed acl util-linux attr app-arch/tar shadow grep libpcre sandbox

export PKGDIR=/var/portage/packages

chroot ${ecroot} emerge --jobs=16 -e -K --with-bdeps=y world

find ${ecroot}/etc -name "._cfg*" | xargs rm

chroot ${ecroot} etc-update

umount ${ecroot}/var/portage

umount ${ecroot}/proc
umount ${ecroot}/dev/pts
umount ${ecroot}/dev
umount ${ecroot}/usr/portage
umount ${ecroot}/run

echo "-----------------------------------------------------"
