#!/bin/bash

ecroot="/var/gentoo/system-gentoo"

mkdir ${ecroot}

CP=$PWD
cd tools
export DIR=_
TEMPLATE=.s.files ../cp-files
cp $DIR/* -r ${ecroot}
rm -r $DIR
cp emerge-cross-system/* -r ${ecroot}
cd $CP

sed s/"-j[0-9]*"/"-j2"/ -i $ecroot/etc/portage/make.conf
sed s/"FEATURES"/"#FEATURES"/ -i $ecroot/etc/portage/make.conf
sed s/"#"// -i $ecroot/etc/portage/profile/package.provided

mkdir -p ${ecroot}/dev ${ecroot}/proc ${ecroot}/run ${ecroot}/var/portage/gentoo ${ecroot}/var/portage/overlay ${ecroot}/var/portage/packages ${ecroot}/var/portage/distfiles ${ecroot}/usr/bin ${ecroot}/usr/lib ${ecroot}/usr/lib64

mount /dev ${ecroot}/dev --bind -o ro
mount -t devpts none ${ecroot}/dev/pts -o gid=5
mount -t proc none ${ecroot}/proc -o ro
mount --bind /var/portage/gentoo ${ecroot}/var/portage/gentoo
mount --bind /var/portage/overlay ${ecroot}/var/portage/overlay -o ro
mount --bind /var/portage/packages ${ecroot}/var/portage/packages -o ro
mount -t tmpfs none ${ecroot}/run

export PKGDIR=${ecroot}/var/portage/packages

export LC_ALL=C
export LANG=C

ROOT=${ecroot} SYSROOT=${ecroot} PORTAGE_CONFIGROOT=${ecroot} emerge --jobs=32 -1 -K --nodeps app-alternatives/awk app-alternatives/bc app-alternatives/bzip2 app-alternatives/cpio app-alternatives/gzip app-alternatives/lex app-alternatives/sh app-alternatives/tar app-alternatives/yacc
ROOT=${ecroot} SYSROOT=${ecroot} PORTAGE_CONFIGROOT=${ecroot} emerge --jobs=32 -1 -K --nodeps coreutils glibc app-arch/bzip2 portage bash ncurses readline python python-exec app-arch/gzip sys-libs/zlib libffi findutils sed acl util-linux attr app-arch/tar shadow grep libpcre sandbox openssl baselayout gcc

export PKGDIR=/var/portage/packages

chroot ${ecroot} emerge --jobs=32 -e -K --with-bdeps=y world

find ${ecroot}/etc -name "._cfg*" | xargs rm

chroot ${ecroot} etc-update

umount ${ecroot}/run
umount ${ecroot}/var/portage/gentoo
umount ${ecroot}/var/portage/overlay
umount ${ecroot}/var/portage/packages
umount ${ecroot}/proc
umount ${ecroot}/dev/pts
umount ${ecroot}/dev
