#!/bin/bash

. /var/gentoo/version

ecroot="/var/gentoo/system-gentoo"

mkdir ${ecroot}

cp settings/system/* -r ${ecroot}

mount /dev/ ${ecroot}/dev/ --bind -o ro
mount -t devpts none ${ecroot}/dev/pts -o gid=5
mount -t proc none ${ecroot}/proc -o ro
mount -o loop /var/gentoo/portage-$P.squashfs ${ecroot}/usr/portage
mount --bind /var/portage/ ${ecroot}/var/portage -o ro
mount -t tmpfs none ${ecroot}/run

export PKGDIR=${ecroot}/var/portage/packages

export LC_ALL=C
export LANG=C

ROOT=${ecroot} SYSROOT=${ecroot} PORTAGE_CONFIGROOT=${ecroot} emerge -e -K system

export PKGDIR=/var/portage/packages

chroot ${ecroot} emerge -e world -K --with-bdeps=y

find ${ecroot}/etc -name "._cfg*" | xargs rm

chroot ${ecroot} etc-update
chroot ${ecroot} eix-update

umount ${ecroot}/var/portage

umount ${ecroot}/proc
umount ${ecroot}/dev/pts
umount ${ecroot}/dev
umount ${ecroot}/usr/portage
umount ${ecroot}/run

echo "-----------------------------------------------------"
