#!/bin/bash

. ./env
. $SYS_PREFIX/var/gentoo/version

mksquashfs $SYS_PREFIX/usr/portage $SYS_PREFIX/var/gentoo/portage-$V.squashfs -b 1M -comp xz
chmod 0644 $SYS_PREFIX/var/gentoo/portage-$V.squashfs
