#!/bin/bash

BP=$(echo "$0" | sed s/$(basename $0)//)

FV=$(ls | grep kernel*.tar.xz | sed s/kernel-// | sed s/.tar.xz//)

if [ "$FV" == "" ] ; then
echo "Kernel not found!"
exit 1
fi

if [ ! -d ./kernel-$FV ] ; then
echo "Unpack kernel..."
tar -xJpf ./kernel-$FV.tar.xz
fi

DIR=ro-temp

mkdir -p $DIR

cp --preserve ./kernel-$FV/boot/ -r $DIR
cp --preserve ./kernel-$FV/usr/ -r $DIR

GC=efi/grub-efi.cfg
[ ! -f "$GC" ] && mkdir -p ./efi && cp $BP/loader/efi/grub-efi.cfg ./efi

. ./env

if [ -f ./ro.include ] ; then
CP=$PWD
. ./ro.include ; RET=$?
cd $CP
[ "$RET" != "0" ] && echo "Error in ro.include!" && exit 1
fi

[ "$NAME" == "" ] && NAME="gentoo"
N="$NAME"

[ -d $DIR/home/user ] && chown 1000:1000 $DIR/home/user -R

mkdir -p ro

[ -f "ro/ro-$N-$FV.squashfs" ] &&  echo "File (ro/ro-$N-$FV.squashfs) exist! Renaming..." && sleep 5 && mv ro/ro-$N-$FV.squashfs ro/ro-$N-$FV.squashfs-

mksquashfs $DIR ro/ro-$N-$FV.squashfs -comp xz

rm -rf $DIR

echo "FV=$FV"
A=$(ls kernel-"$FV"/boot | grep vmlinuz | sed s/"-r[0-9][0-9]*"// | cut -d '-' -f 4 | sed s/"+"//)
echo "A=$A"
KV=$(echo "$FV" | cut -d'-' -f 1)
echo "KV=$KV"
KN=$(echo "$FV" | sed s/"-r[0-9][0-9]*"//g | sed s/"$A"// | cut -d '-' -f 2)
echo "KN=$KN"
KR=$(echo "$FV" | sed s/"-$KN-"/-/ | cut -d'-' -f 2 | sed s/"$A"//)
echo "KR=$KR"
V=$(echo "$FV" | sed s/"$KV"// | sed s/"-$KN-"/-/ | sed s/"-$KR-"/-/ | sed s/"-$A-"//)
echo "V=$V"
[ "$SV" == "" ] && SV=$(echo "$V" | cut -d'-' -f 1)
echo "SV=$SV"

[ "$SN" != "" ] && SN=-"$SN"

sed s/kv=.*$/kv=$KV/ -i $GC
sed s/arch=.*$/arch=$A/ -i $GC
sed s/lsystem=.*$/lsystem=system-$NAME$SN-'$arch'-$SV.squashfs/ -i $GC
[ "$KR" != "" ] && sed s/kr=.*$/"kr=-$KR"/ -i $GC
[ "$KN" != "" ]  && sed s/lro=.*$/lro=ro-$N-'$kv'-$KN'$kr'-'$arch'-$V.squashfs/ -i $GC || sed s/lro=.*$/lro=ro-$N-'$kv$kr'-'$arch'-$V.squashfs/ -i $GC
sed s/rw-overlay/rw-$NAME/ -i $GC

echo "kernel: $FV"
