#!/bin/bash

. ../env
. $SYS_PREFIX/var/gentoo/version

export DIR="kernel-$KV-$A-$V$R"
TEMPLATE=.a-files ../cp-files

cd $SYS_PREFIX/var/gentoo/kernel && tar -cf $DIR.tar $DIR && xz -9 -T0 -v $DIR.tar

rm -rf "$DIR"
