#!/bin/bash

. ./env

[ "$NAME" == "" ] && NAME="gentoo"

P="../ofs-boot"

$P/mk-loader
$P/mk-ro
RW_SIZE=512M $P/mk-rw
mkdir -p linux/system
mv ro linux/
mv rw linux/
N="$(ls kernel*.tar.xz | sed s/kernel/boot-$NAME/ | sed s/.tar.xz$// | sed s/"-r[0-9]*$"//)$R.tar"
tar -cf "$N" efi linux && xz -T0 -v "$N"
rm -r efi linux
