#!/bin/sh

[ -f /usr/local/sbin/init-video ] && /usr/local/sbin/init-video

if [ "$(cat /proc/cmdline | grep " splash")" != "" ] ; then
 mkdir /run/plymouth
 chvt 16
 /sbin/plymouthd --tty=tty16 --attach-to-session --pid-file=/run/plymouth/pid --mode=boot
 plymouth show-splash
fi

[ -f /usr/local/sbin/0-init ] && . /usr/local/sbin/0-init

exec /sbin/init "$*"
